services:
  contactdb:
    image: mysql:8.4
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 9984
      MYSQL_DATABASE: contactdb_compose
      MYSQL_USER: mysql
      MYSQL_PASSWORD: 9984
    networks:
      - default

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - default

networks:
  default:
    driver: bridge
